In [9]:
import pandas as pd
import requests
import os
from nba_api.stats.static import players,teams


series=pd.read_csv('https://raw.githubusercontent.com/gabriel1200/nba_rapm/main/playoff_series.csv')
series=series[series.year>=2014]

frames=[]
for year in range(2014,2025):
    frame=pd.read_csv(str(year)+'.csv')
    frame2=pd.read_csv(str(year)+'_2.csv')
    joined_columns = set(frame2.columns) - set(frame.columns)
    joined_columns = list(joined_columns)
    joined_columns.append('PLAYER_ID')
    joined_columns.append('date')
    frame2 = frame2[joined_columns]
    frame=frame.merge(frame2,on=['PLAYER_ID','date'],how='left')
    frames.append(frame)
df=pd.concat(frames),
df.drop_duplicates(inplace=True)
print(len(df))
def get_dates():
    dates=[]
    for year in range(2014,2025):
    
        for team in teams.get_teams():
            team_id=team['id']
            path = '../team/'+str(year)+'ps/'+str(team_id)+'.csv'
            if os.path.exists(path):
                df=pd.read_csv(path)
    
                df=df[['PLAYER_ID','TEAM_ID','HTM','VTM','GAME_DATE']]
                df.rename(columns={'GAME_DATE':'date'},inplace=True)
                df.drop_duplicates(inplace=True)
                dates.append(df)
    return pd.concat(dates)
dates=get_dates()
df=df.merge(dates,how='left').reset_index(drop=True)
home=df[df.HTM==df.TEAM_ABBREVIATION].reset_index(drop=True)
home.drop(columns='HTM',inplace=True)

home.rename(columns={'VTM':'opp_team'},inplace=True)


home

away=df[df.VTM==df.TEAM_ABBREVIATION].reset_index(drop=True)
away.drop(columns='VTM',inplace=True)
away.rename(columns={'HTM':'opp_team'},inplace=True)

away

none=df[df.HTM.isna()].reset_index(drop=True)
#none.drop(columns=['VTM','HTM'],inplace=True)
df=pd.concat([home,away,none])


oppframe=df[['TEAM_ID','date','opp_team']]
oppframe.dropna(subset='opp_team',inplace=True)
oppframe.drop_duplicates(inplace=True)
df.drop(columns='opp_team',inplace=True)

#df=df.merge(oppframe)
df

df=df.merge(oppframe,on=['TEAM_ID','date'],how='left')
df

TypeError: unhashable type: 'list'

In [2]:
none2=df[df.opp_team.isna()]
df=df.dropna(subset='opp_team')
teammap=dict(zip(df['TEAM_ABBREVIATION'],df['TEAM_ID']))

df['opp_id']=df['opp_team'].map(teammap)
df.to_csv('playoff_data.csv',index=False)

/tmp/ipykernel_20418/2211292126.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['opp_id']=df['opp_team'].map(teammap)

In [3]:
df[df.TEAM_ABBREVIATION=='DET']
df['team']=df['TEAM_ABBREVIATION']

/tmp/ipykernel_20418/2916735606.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['team']=df['TEAM_ABBREVIATION']

In [4]:
df.sort_values(by='date',inplace=True)

df['series_key']=df['team']+'_'+df['opp_team']+'_'+df['year'].astype(str)
df

/tmp/ipykernel_20418/1847432245.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by='date',inplace=True)
/tmp/ipykernel_20418/1847432245.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['series_key']=df['team']+'_'+df['opp_team']+'_'+df['year'].astype(str)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,FGA_LT_06,FGM_35_39,FGP_35_39,FGP_40_PLUS,HTM,VTM,opp_team,opp_id,team,series_key
0,101161,Amir Johnson,Amir,1610612761,TOR,27.0,1,0,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,BKN,1610612751,TOR,TOR_BKN_2014
113424,2419,Tayshaun Prince,Tayshaun,1610612763,MEM,34.0,1,0,1,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,OKC,1610612760,MEM,MEM_OKC_2014
113423,2581,Steve Blake,Steve,1610612744,GSW,34.0,1,1,0,1.0,...,2.0,NaN,NaN,NaN,NaN,NaN,LAC,1610612746,GSW,GSW_LAC_2014
113422,2581,Steve Blake,Steve,1610612744,GSW,34.0,1,1,0,1.0,...,3.0,NaN,NaN,NaN,NaN,NaN,LAC,1610612746,GSW,GSW_LAC_2014
113421,2581,Steve Blake,Steve,1610612744,GSW,34.0,1,1,0,1.0,...,2.0,NaN,NaN,NaN,NaN,NaN,LAC,1610612746,GSW,GSW_LAC_2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107618,201143,Al Horford,Al,1610612738,BOS,38.0,1,1,0,1.0,...,7.0,NaN,NaN,NaN,NaN,NaN,DAL,1610612742,BOS,BOS_DAL_2024
107619,201143,Al Horford,Al,1610612738,BOS,38.0,1,1,0,1.0,...,8.0,NaN,NaN,NaN,NaN,NaN,DAL,1610612742,BOS,BOS_DAL_2024
107620,201143,Al Horford,Al,1610612738,BOS,38.0,1,1,0,1.0,...,13.0,NaN,NaN,NaN,NaN,NaN,DAL,1610612742,BOS,BOS_DAL_2024
107622,201143,Al Horford,Al,1610612738,BOS,38.0,1,1,0,1.0,...,19.0,NaN,NaN,NaN,NaN,NaN,DAL,1610612742,BOS,BOS_DAL_2024
218331,1629023,P.J. Washington,P.J.,1610612742,DAL,25.0,1,0,1,0.0,...,89.0,NaN,NaN,NaN,NaN,NaN,BOS,1610612738,DAL,DAL_BOS_2024

In [5]:
for key in df['series_key'].unique():
    series=df[df.series_key==key]
    series.to_csv('data/'+key+'.csv',index=False)

In [6]:
series=pd.read_csv('https://raw.githubusercontent.com/gabriel1200/nba_rapm/main/playoff_series.csv')
series.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT',
       ...
       'OPP_TS_PCT', 'rs_OPP_OFF_RATING', 'rs_OPP_DEF_RATING',
       'rs_OPP_ROFF_RATING', 'rs_OPP_RDEF_RATING', 'year_avg_ts',
       'rOPP_TS_PCT', 'rTS_PCT', 'ADJ_OFF_RATING', 'ADJ_DEF_RATING'],
      dtype='object', length=137)

In [7]:
series['OPP_ID']

series=series[['PLAYER_ID','TEAM_ID','OPP_ID']]
series.to_csv('series_index.csv',index=False)